name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run code quality checks
      run: |
        poetry run ruff .
        poetry run mypy .

    - name: Run tests
      run: |
        poetry run pytest

    - name: Generate Coverage Report
      run: |
        poetry run pytest --cov=gitmuse --cov-report=xml
      continue-on-error: true

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml
